# Generated by Django 2.1 on 2018-10-26 17:45

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import fileuploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('directory_name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('file_content', djongo.models.fields.ArrayModelField(model_container=fileuploads.models.SentenceItem)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=200)),
                ('directory', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.DO_NOTHING, to='fileuploads.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=200)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('file_content', djongo.models.fields.ArrayModelField(model_container=fileuploads.models.QueryItem)),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='file',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='fileuploads.ResultFile'),
        ),
    ]
