# Generated by Django 2.1 on 2018-10-26 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0002_auto_20181026_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfile',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
